[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
doctest = false
bench = false


[dependencies]
#spin = "0.10.0"
#talc = { version = "4.4.3", default-features = false, features = ["lock_api"] }

cfg-if = "1.0.4"
static_assertions = "1.1.0"

sbi = "0.3.0"
riscv = { version = "0.15.0", features = ["s-mode", "critical-section-single-hart"] }
#riscv-rt = { version = "0.16.0", features = ["s-mode", "single-hart"] }
embedded-alloc = { version = "0.6.0" }
fdt = "0.1.5"
heapless = "0.9.3"
spin = { version = "0.12.0", default-features = false, features = ["mutex", "spin_mutex", "rwlock", "once", "lazylock", "barrier"] }
bitfield-struct = "0.13.0"
bitmap-allocator = "0.4.5"
sync-unsafe-cell = "0.1.1"

[build-dependencies]
llvm-tools = "0.1.1"
